# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 04:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_guidebox_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='guidebox_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='guidebox_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
