# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160528_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='guidebox_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
