# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_loc',
        ),
        migrations.AddField(
            model_name='movie',
            name='has_poster',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
