# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20160604_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
